#!/usr/bin/env bash

if [ -z "${KUBECONFIG}" ]; then
    export KUBECONFIG=~/.kube/config
fi

# CAUTION - setting NAMESPACE will deploy most components to the given namespace
# however some are hardcoded to 'monitoring'. Only use if you have reviewed all manifests.

if [ -z "${NAMESPACE}" ]; then
    NAMESPACE=logging
fi

kubectl create namespace "$NAMESPACE"

kctl() {
    kubectl --namespace "$NAMESPACE" "$@"
}
# alias kctl='kubectl --namespace logging'

# Deploy etcd operator
kctl apply -f etcd-operator-rbac.yaml
kctl apply -f etcd-operator-deployment.yaml

sleep 20
# Deploy etcd cluster for Traefik
kctl apply -f etcd-traefik-svc.yaml
kctl apply -f etcd-traefik-cluster.yaml

sleep 20
# Deploy Traefik RBAC
kctl apply -f traefik-rbac.yaml

# Deploy internal Traefik and it's config
kctl apply -f traefik-internal-configmap.yaml
kctl apply -f traefik-internal-service.yaml
kctl apply -f traefik-internal-deployment.yaml

# Deploy external Traefik config and store the config into etcd KV
kctl apply -f external-traefik-configmap.yaml
kctl apply -f external-traefik-store-KV.yaml

# Deploy external Traefik and it's service
kctl apply -f external-traefik-service.yaml
kctl apply -f external-traefik-statefulset.yaml

sleep 20
# Delete job since config was already loaded into KV
kctl delete -f external-traefik-store-KV.yaml

