#!/usr/bin/env bash

if [ -z "${KUBECONFIG}" ]; then
    export KUBECONFIG=~/.kube/config
fi

# CAUTION - setting NAMESPACE will deploy most components to the given namespace
# however some are hardcoded to 'monitoring'. Only use if you have reviewed all manifests.

if [ -z "${NAMESPACE}" ]; then
    NAMESPACE=traefik
fi

kubectl create namespace "$NAMESPACE"

kctl() {
    kubectl --namespace "$NAMESPACE" "$@"
}

if ! [ -x "$(command -v helm)" ]; then
  echo 'Error: helm is not installed.' >&2
  exit 1
fi

helm install --name traefik stable/consul

sleep 20
# Deploy Traefik RBAC
kctl apply -f traefik-rbac.yaml

# Deploy internal Traefik and it's config
kctl apply -f traefik-internal-configmap.yaml
kctl apply -f traefik-internal-service.yaml
kctl apply -f traefik-internal-deployment.yaml

# Deploy external Traefik config
kctl apply -f external-traefik-configmap.yaml

# Deploy external Traefik and it's service
kctl apply -f external-traefik-service.yaml
kctl apply -f external-traefik-statefulset.yaml
